version: 2

models:
  - name: stg_epl_matches
    description: 'Staged English Premier League'

    columns:
      - name: home_team
        tests:
          - not_null
      - name: away_team
        tests:
          - not_null
      - name: home_score
        tests: 
          - not_null
      - name: away_score
        tests:
          - not_null
